name: Publish Electron Binaries

on:
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build-electron-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Build UI
        working-directory: ./ui
        run: |
          npm ci
          npm run build-desktop
      - name: Build deb, rpm
        working-directory: ./electron
        run: |
          npm ci
          npm run publish
  build-electron-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Build UI
        working-directory: ./ui
        run: |
          npm ci
          npm run build-desktop
      - name: Build windows installer
        working-directory: ./electron
        run: |
          npm ci
          npm run publish
  build-electron-mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Build UI
        working-directory: ./ui
        run: |
          npm ci
          npm run build-desktop
      - name: Build macos binaries
        working-directory: ./electron
        run: |
          npm ci
          npm run publish
