name: Publish Electron Binaries

on:
  workflow_dispatch:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build-electron-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Build UI
        working-directory: ./packages/ui
        run: |
          npm ci
          npm run build-desktop
      - name: Build deb, rpm
        working-directory: ./packages/electron
        run: |
          npm ci
          npm run publish
  build-electron-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Build UI
        working-directory: ./packages/ui
        run: |
          npm ci
          npm run build-desktop
      - name: Build windows installer
        working-directory: ./packages/electron
        run: |
          npm ci
          npm run publish
  build-electron-mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Build UI
        working-directory: ./packages/ui
        run: |
          npm ci
          npm run build-desktop
      - name: Add MacOS certs
        run: chmod +x scripts/add-osx-cert.sh && ./scripts/add-osx-cert.sh
        env:
          CERTIFICATE_OSX_APPLICATION: ${{ secrets.CERTIFICATE_OSX_APPLICATION }}
          CERTIFICATE_PASSWORD: ${{ secrets.CERTIFICATE_PASSWORD }}
      - name: Build macos binaries
        working-directory: ./packages/electron
        env:
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_ID_PASSWORD: ${{ secrets.APPLE_ID_PASSWORD }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
        run: |
          npm ci
          npm run publish
